### ISSUE TITLE
Test quiver w.r.t zk connection loss

### ISSUE THREAD

**Issue by dt** [foursquare/quiver#49]
ideally we shouldn't exit until many repeated attempts to reconnect have failed.

That said, we _should_ probably exit once it becomes clear we won't reconnect -- we're useless if we're not in service disco, and exiting non-zero will cause the scheduler (eg aurora) to reschedule us, and then the new proc will hopefully be able to talk to ZK.

**Comment by dt** [comment]
btw, here's the stderr of a proc that exited when we lost zk:

```
2015/12/08 13:37:44 Watching paths for killfile: [/dev/shm/healthz/kill.30619 /dev/shm/healthz/kill.all]
2015/12/08 13:37:44 Waiting to join service discovery 0
2015/12/08 13:37:44 Joining service discovery...
2015/12/08 13:37:44 Creating 9 registration fsax45.prod.foursquare.com:30619 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/9/131bc0bb-4e3f-48cc-bd28-473ecd3fe65d
2015/12/08 13:37:44 Creating 9t registration fsax45.prod.foursquare.com:30386 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/9t/460f05c7-baff-4611-8432-4e6d21cd6d51
2015/12/08 13:37:44 Creating 10 registration fsax45.prod.foursquare.com:30619 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/10/10a87701-14d2-47de-8300-dbc485525441
2015/12/08 13:37:44 Creating 10t registration fsax45.prod.foursquare.com:30386 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/10t/f91fb47c-65ca-43c3-988d-50d2244892c3
2015/12/08 13:37:44 Creating 11 registration fsax45.prod.foursquare.com:30619 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/11/0222fe64-fdc9-4d86-b838-b7713bb98ec5
2015/12/08 13:37:44 Creating 11t registration fsax45.prod.foursquare.com:30386 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/11t/f3e33f3b-4533-454b-8eb0-1bb5c06452ac
2015/12/08 13:37:44 Listening for raw RPC on 30386
2015/12/08 21:28:23 Recv loop terminated: err=read tcp 10.1.24.45:60626->10.1.10.27:2181: i/o timeout
2015/12/08 21:28:23 Send loop terminated: err=<nil>
2015/12/08 21:28:24 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:28:25 Failed to connect to 10.1.10.3:2181: dial tcp 10.1.10.3:2181: i/o timeout
2015/12/08 21:28:26 Failed to connect to 10.1.6.26:2181: dial tcp 10.1.6.26:2181: i/o timeout
2015/12/08 21:28:27 Failed to connect to 10.1.6.24:2181: dial tcp 10.1.6.24:2181: i/o timeout
2015/12/08 21:28:29 Failed to connect to 10.1.10.27:2181: dial tcp 10.1.10.27:2181: i/o timeout
2015/12/08 21:28:30 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:28:31 Failed to connect to 10.1.10.3:2181: dial tcp 10.1.10.3:2181: i/o timeout
2015/12/08 21:28:32 Failed to connect to 10.1.6.26:2181: dial tcp 10.1.6.26:2181: i/o timeout
2015/12/08 21:28:33 Failed to connect to 10.1.6.24:2181: dial tcp 10.1.6.24:2181: i/o timeout
2015/12/08 21:28:35 Failed to connect to 10.1.10.27:2181: dial tcp 10.1.10.27:2181: i/o timeout
2015/12/08 21:28:36 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:28:37 Failed to connect to 10.1.10.3:2181: dial tcp 10.1.10.3:2181: i/o timeout
2015/12/08 21:28:38 Failed to connect to 10.1.6.26:2181: dial tcp 10.1.6.26:2181: i/o timeout
2015/12/08 21:28:39 Failed to connect to 10.1.6.24:2181: dial tcp 10.1.6.24:2181: i/o timeout
2015/12/08 21:28:41 Failed to connect to 10.1.10.27:2181: dial tcp 10.1.10.27:2181: i/o timeout
2015/12/08 21:28:42 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:28:43 Failed to connect to 10.1.10.3:2181: dial tcp 10.1.10.3:2181: i/o timeout
2015/12/08 21:28:44 Failed to connect to 10.1.6.26:2181: dial tcp 10.1.6.26:2181: i/o timeout
2015/12/08 21:28:45 Failed to connect to 10.1.6.24:2181: dial tcp 10.1.6.24:2181: i/o timeout
2015/12/08 21:28:47 Failed to connect to 10.1.10.27:2181: dial tcp 10.1.10.27:2181: i/o timeout
2015/12/08 21:28:48 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:28:49 Failed to connect to 10.1.10.3:2181: dial tcp 10.1.10.3:2181: i/o timeout
2015/12/08 21:28:50 Failed to connect to 10.1.6.26:2181: dial tcp 10.1.6.26:2181: i/o timeout
2015/12/08 21:28:51 Failed to connect to 10.1.6.24:2181: dial tcp 10.1.6.24:2181: i/o timeout
2015/12/08 21:28:53 Failed to connect to 10.1.10.27:2181: dial tcp 10.1.10.27:2181: i/o timeout
2015/12/08 21:28:54 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:28:55 Failed to connect to 10.1.10.3:2181: dial tcp 10.1.10.3:2181: i/o timeout
2015/12/08 21:28:56 Failed to connect to 10.1.6.26:2181: dial tcp 10.1.6.26:2181: i/o timeout
2015/12/08 21:28:57 Failed to connect to 10.1.6.24:2181: dial tcp 10.1.6.24:2181: i/o timeout
2015/12/08 21:28:59 Failed to connect to 10.1.10.27:2181: dial tcp 10.1.10.27:2181: i/o timeout
2015/12/08 21:29:00 Failed to connect to 10.1.12.30:2181: dial tcp 10.1.12.30:2181: i/o timeout
2015/12/08 21:29:00 Connected to 10.1.10.3:2181
2015/12/08 21:29:00 Reconnected. Re-registering services.
2015/12/08 21:29:00 Creating 11 registration fsax45.prod.foursquare.com:30619 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/11/0222fe64-fdc9-4d86-b838-b7713bb98ec5
2015/12/08 21:29:00 Connection attempt unsuccessful after 37.009171923s (greater than max timeout of 15s). Resetting connection and trying again with a new connection.
2015/12/08 21:29:00 Reconnected. Re-registering services.
2015/12/08 21:29:00 Creating 9 registration fsax45.prod.foursquare.com:30619 (attempt 1): /foursquare/discovery/hfileservice/rankable_venues_12/com.foursquare.hfile.rpc.common.ModShard/12/9/131bc0bb-4e3f-48cc-bd28-473ecd3fe65d
2015/12/08 21:29:00 Connection attempt unsuccessful after 37.009283674s (greater than max timeout of 15s). Resetting connection and trying again with a new connection.
panic: close of closed channel

goroutine 112 [running]:
github.com/samuel/go-zookeeper/zk.(*Conn).Close(0xc8200d01c0)
    /tmp/foo/src/github.com/samuel/go-zookeeper/zk/conn.go:228 +0x37
github.com/foursquare/curator%2ego.(*handleHolder).internalClose(0xc8200148c0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/state.go:117 +0x88
github.com/foursquare/curator%2ego.(*handleHolder).closeAndReset(0xc8200148c0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/state.go:103 +0x31
github.com/foursquare/curator%2ego.(*connectionState).reset(0xc82004e690, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/state.go:214 +0x77
github.com/foursquare/curator%2ego.(*connectionState).checkTimeout(0xc82004e690, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/state.go:250 +0x29a
github.com/foursquare/curator%2ego.(*connectionState).Conn(0xc82004e690, 0x0, 0x0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/state.go:183 +0xac
github.com/foursquare/curator%2ego.(*curatorZookeeperClient).Conn(0xc82004cbc0, 0x0, 0x0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/client.go:204 +0x138
github.com/foursquare/curator%2ego.(*createBuilder).pathInForeground.func1(0x0, 0x0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/create.go:73 +0x98
github.com/foursquare/curator%2ego.(*retryLoop).CallWithRetry(0xc821d97500, 0xc821128e10, 0x0, 0x0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/retry.go:74 +0x50
github.com/foursquare/curator%2ego.(*createBuilder).pathInForeground(0xc821d974a0, 0xc820fb3440, 0x88, 0xc823547200, 0xd5, 0x109, 0x0, 0x0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/create.go:88 +0x19c
github.com/foursquare/curator%2ego.(*createBuilder).ForPathWithData(0xc821d974a0, 0xc820fb3440, 0x88, 0xc823547200, 0xd5, 0x109, 0x0, 0x0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/curator.go/create.go:36 +0x2bc
github.com/foursquare/fsgo/net/discovery.(*ServiceDiscovery).Register(0xc8200141e0, 0xc82004e460, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/fsgo/net/discovery/service.go:119 +0x535
github.com/foursquare/fsgo/net/discovery.(*ServiceDiscovery).ReregisterAll(0xc8200141e0, 0x0, 0x0)
    /tmp/foo/src/github.com/foursquare/fsgo/net/discovery/service.go:139 +0x9d
github.com/foursquare/fsgo/net/discovery.(*ServiceDiscovery).maintainConn(0xc8200141e0)
    /tmp/foo/src/github.com/foursquare/fsgo/net/discovery/service.go:90 +0x135
created by github.com/foursquare/fsgo/net/discovery.(*ServiceDiscovery).MaintainRegistrations
    /tmp/foo/src/github.com/foursquare/fsgo/net/discovery/service.go:62 +0x45
```
